### ISSUE TITLE
Binary Search is not working if we have a same number 2 times. 

### ISSUE THREAD

**Issue by Himnashu** [Lekheshwar/Algo-Visualizer#1]
<img width="1420" alt="Screenshot 2020-08-07 at 1 58 51 AM" src="https://user-images.githubusercontent.com/53173981/89579779-fb66f280-d851-11ea-8fdd-d833343e1014.png">

**Comment by Lekheshwar** [comment]
I think it is working well, couldn't find an issue.
![Screenshot (18)](https://user-images.githubusercontent.com/66664839/89762841-df43a980-db0e-11ea-85e4-c4831140051a.png)
